version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: qualoplano-api
    container_name: qualoplano-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    environment:
      DYNAMODB_ENDPOINT: 'http://dynamodb-local:8000'
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - app-network

networks:
  app-network:
    driver: bridge